name: URL Speed Test with Channel Preservation and Top 20 URLs

# 控制触发此工作流的时间表
on:
  schedule:
    - cron: '0 6 * * *'  # 每天凌晨6点执行
  workflow_dispatch:  # 允许手动触发

jobs:
  speed-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run speed test script
      run: |
        python speed_test.py

    - name: Upload speed-live.txt as artifact
      uses: actions/upload-artifact@v3
      with:
        name: speed-live
        path: speed-live.txt
